/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <unistd.h>

/*
 * Definizione dei fileni se non già definiti in unistd.h
 * (alcuni toolchain non includono <unistd.h> di default)
 */
#ifndef STDIN_FILENO
#define STDIN_FILENO  0
#endif
#ifndef STDOUT_FILENO
#define STDOUT_FILENO 1
#endif
#ifndef STDERR_FILENO
#define STDERR_FILENO 2
#endif

/*
 * Includi i file che contengono l'handle della tua UART.
 * Esempio: se CubeIDE ha generato "usart.h" contenente huart3,
 * allora:
 */

#include <string.h>
#include "main.h"
#include "gpio.h"
#include "usart.h"   // O il file dove è dichiarato UART_HandleTypeDef huart3
#include "stm32f7xx_hal.h"

extern UART_HandleTypeDef huart3;

/* Variabili deboli di default */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));

char *__env[1] = { 0 };
char **environ = __env;

/* Funzioni generate */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

/*
 * Commentiamo (o rimuoviamo) eventuali versioni _weak di _read/_write
 * che erano presenti di default, per evitare conflitti
 */
#if 0
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;
  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }
  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;
  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}
#endif

int _write(int file, char *ptr, int len)
{

  if (file == STDOUT_FILENO || file == STDERR_FILENO)
  {
    if(HAL_UART_Transmit(&huart3, (uint8_t *)ptr, len, HAL_MAX_DELAY) != HAL_OK) {
        errno = EIO;  // Oppure un altro codice d'errore appropriato
        return -1;
    }

    return len;
  }

  errno = EBADF;
  return -1;
}

/**
  * @brief  Reindirizza la lettura (scanf) dalla UART.
  */
int _read(int file, char *ptr, int len)
{
    if (file == STDIN_FILENO)
    {
        int bytesRead = 0;

        // Leggiamo carattere per carattere, facciamo eco e gestiamo il backspace
        for (int i = 0; i < len; i++)
        {
            uint8_t c;
            // Lettura bloccante di un carattere
            if (HAL_UART_Receive(&huart3, &c, 1, HAL_MAX_DELAY) != HAL_OK)
            {
                errno = EIO;
                return -1;
            }

            // Gestione del ritorno a capo
            if (c == '\r' || c == '\n')
            {
                // A volte minicom invia solo '\r', oppure '\n': li unifichiamo
                // e interrompiamo la lettura per restituire la riga
                uint8_t newline = '\n';
                HAL_UART_Transmit(&huart3, &newline, 1, HAL_MAX_DELAY);
                ptr[bytesRead++] = '\n';
                break;
            }
            // Gestione del backspace (ASCII 8 oppure 127)
            else if (c == '\b' || c == 127)
            {
                if (bytesRead > 0)
                {
                    // Cancella carattere precedente dal buffer
                    bytesRead--;

                    // Cancella il carattere visualizzato (backspace + spazio + backspace)
                    uint8_t bsSequence[] = "\b \b";
                    HAL_UART_Transmit(&huart3, bsSequence, sizeof(bsSequence) - 1, HAL_MAX_DELAY);
                }
                else
                {
                    // Se non ci sono caratteri, ignoriamo il backspace
                    // (oppure potresti far suonare un beep, ecc.)
                }
            }
            else
            {
                // Esegui l’eco del carattere
                HAL_UART_Transmit(&huart3, &c, 1, HAL_MAX_DELAY);
                // Memorizza il carattere nel buffer
                ptr[bytesRead++] = c;
            }
        }

        return bytesRead;
    }
    else
    {
        errno = EBADF;
        return -1;
    }
}

int _close(int file)
{
  (void)file;
  return -1;
}

int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
